# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Keycard
description: Keycard is a new type of smartcard built with an open API for simple integration with crypto wallets and hardware. Designed to safely send, store, and receive cryptocurrencies in a seamless contactless experience.
author: Status Research & Development GmbH

language: [en, de]
locale: en
i18n:
  type: [page, post]
permalink_defaults:
  lang: en
i18n_dir: :lang

header:
  menu:
    why:
      title: Why
    features:
      title: Features
    security:
      title: Security
    keycard:
      title: Keycard API
    about:
      title: About us

menubutton: Get Keycard

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://keycard.status.im/
root: /
permalink: :year/:month/:day/:title/
post_asset_folder: true

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: keycard

autoprefixer:
  enable: true
  browsers:
    - 'last 2 versions'
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false